# Generated by Django 5.1 on 2024-08-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Created_date', models.CharField(max_length=50)),
                ('Diagnostics', models.CharField(max_length=50)),
                ('Observations', models.CharField(max_length=50)),
                ('Treatments', models.CharField(max_length=50)),
                ('Misc', models.CharField(blank=True, max_length=200)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.department')),
                ('Doctor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_user.doctors_detail')),
                ('Patient_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth_user.patients_detail')),
            ],
        ),
    ]
