# Generated by Django 5.1 on 2024-08-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Diagnostics', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.department')),
            ],
        ),
    ]
