# Generated by Django 5.1 on 2024-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_detail',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patients_detail',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
